<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Xacro properties for standoff_rod dimensions -->
  <xacro:property name="rod_radius" value="0.01"/>
  <xacro:property name="rod_length" value="0.22"/>
  <xacro:property name="rod_mass" value="0.2"/>

  <!-- Standoff Rod Macro -->
  <xacro:macro name="standoff_rod" params="prefix parent_link *origin">

    <!-- Standoff Rod Link -->
    <link name="${prefix}_rod">
      <visual>
        <origin xyz="0 0 ${rod_length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${rod_radius}" length="${rod_length}"/>
        </geometry>
        <material name="white"/>
      </visual>

      <collision>
        <origin xyz="0 0 ${rod_length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${rod_radius}" length="${rod_length}"/>
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 ${rod_length/2}" rpy="0 0 0"/>
        <mass value="${rod_mass}"/>
        <!-- Cylinder inertia: Ixx = Iyy = (1/12)*m*(3*r^2 + h^2), Izz = (1/2)*m*r^2 -->
        <inertia ixx="${(1/12) * rod_mass * (3 * rod_radius * rod_radius + rod_length * rod_length)}" ixy="0.0" ixz="0.0" iyy="${(1/12) * rod_mass * (3 * rod_radius * rod_radius + rod_length * rod_length)}" iyz="0.0" izz="${(1/2) * rod_mass * rod_radius * rod_radius}"/>
      </inertial>
    </link>

    <!-- Standoff Rod Joint -->
    <joint name="${prefix}_rod_joint" type="fixed">
      <parent link="${parent_link}"/>
      <child link="${prefix}_rod"/>
      <xacro:insert_block name="origin"/>
    </joint>

    <!-- Gazebo Properties -->
    <gazebo reference="${prefix}_rod">
      <material>Gazebo/White</material>
    </gazebo>

  </xacro:macro>

</robot>
